### ISSUE TITLE
Cannot download NuGet packages from GitHub Packages source

### ISSUE THREAD

**Issue by buzhaodi** [ipphone/core#101]
When I tried to compile, an error was reported that no package with ipphone.pjsipdll greater than 1.13.3 was found. How to solve it ？

**Comment by alexrster** [comment]
Hi @buzhaodi,

I'm sorry for the late response! To overcome this issue you have to register GitHub Packages source on your box.

Here is the guide: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#installing-a-package

Here is the link to missing package: https://github.com/ipphone/pjsip/packages/259958?version=1.13.3

Thanks for raising this up - 'F5 experience' is very important as for me! I'll keep it open if you don't mind.
