### ISSUE TITLE
Unauthorized SIP

### ISSUE THREAD

**Issue by iGuihP** [ipphone/core#102]
Hello!

I'm trying to use a SIP trunk which however is giving "unauthorized".
As the credentials are correct, even 'MicroSIP' doesn't work normally.
![Screenshot_1](https://user-images.githubusercontent.com/65922242/158294961-06219064-fb04-44f4-ac6d-b1208ccc9f5b.png)

**Comment by alexrster** [comment]
Well, if it doesn't work with other SIP clients, I assume there is a problem with credentials
