### ISSUE TITLE
Error can not start project

### ISSUE THREAD

**Issue by TechGuyVN** [ipphone/core#25]
Hi,

Thanks for framework, when i download source and start it throw error, please help:
```
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: mscorlib v4.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: System.Windows.Forms v4.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: ExceptionReporter.Core v1.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: PresentationFramework v4.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: ContactPoint.Common v1.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: System v4.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: System.Drawing v4.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: ComponentFactory.Krypton.Toolkit v4.4.1.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: System.Design v4.0.0.0; method: PartLoading in class Program
'ContactPoint.exe' (CLR v4.0.30319: ContactPoint.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Design\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Design.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: ContactPoint.BaseDesign v1.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: Newtonsoft.Json v8.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: ContactPoint.BaseDesign.WPF v1.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: System.Core v4.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: ContactPoint.Core v1.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Load dependency: PresentationCore v4.0.0.0; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Initialize Exception Reporter; method: PartLoading in class Program
'ContactPoint.exe' (CLR v4.0.30319: ContactPoint.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Initialize WPF Infrastructure; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Create WPF Application; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Create WPF Window; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Core infrastructure; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:10: Part loading: Initializing Core; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:11: Part loading: Loading Settings...; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:11: Part loading: Loading SIP...; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/09/2020 11:19:11: Initializing SIP core; method: .ctor in class SIP
ContactPoint.exe Error: 0 : [Error] 04/09/2020 11:19:11: Unable to load DLL 'pjsipDll.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) in onBuddyStatusChangedCallback
ContactPoint.exe Error: 0 : 'ContactPoint.exe' (CLR v4.0.30319: ContactPoint.exe): Loaded 'C:\Omi\Binaries\ContactPoint.Contacts.dll'. Symbols loaded.
'ContactPoint.exe' (CLR v4.0.30319: ContactPoint.exe): Loaded 'C:\Omi\Binaries\SipekSdk.dll'. Symbols loaded.
Exception thrown: 'System.DllNotFoundException' in SipekSdk.dll
[Error] 04/09/2020 11:19:11: Unable to load DLL 'pjsipDll.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) in onBuddyStatusChangedCallback
The program '[8308] ContactPoint.exe' has exited with code 0 (0x0).
```

**Comment by alexrster** [comment]
Hi,

Glad that u find it useful! :)
Please make sure that actual `pjsipDll.dll` is present in `Binaries` folder, if not – copy it manually from: `core/ContactPoint/pjsipDll.dll`

**Comment by TechGuyVN** [comment]
Many Thanks @alexrster 
I did it and that error solved, but when start it still have problem, can you give me suggest ?
`'ContactPoint.exe' (CLR v4.0.30319: ContactPoint.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:58: Part loading: Initialize WPF Infrastructure; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:58: Part loading: Create WPF Application; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:58: Part loading: Create WPF Window; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:58: Part loading: Core infrastructure; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:58: Part loading: Initializing Core; method: PartLoading in class Program
'ContactPoint.exe' (CLR v4.0.30319: ContactPoint.exe): Loaded 'C:\Omi\Binaries\ContactPoint.Contacts.dll'. Symbols loaded.
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:58: Part loading: Loading Settings...; method: PartLoading in class Program
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:58: Part loading: Loading SIP...; method: PartLoading in class Program
'ContactPoint.exe' (CLR v4.0.30319: ContactPoint.exe): Loaded 'C:\Omi\Binaries\SipekSdk.dll'. Symbols loaded.
ContactPoint.exe Information: 0 : [Notice] 04/10/2020 17:18:59: Initializing SIP core; method: .ctor in class SIP
Exception thrown: 'System.InvalidOperationException' in ContactPoint.Core.dll
ContactPoint.exe Error: 0 : [Error] 04/10/2020 17:19:00: Can't initialize PjSIP proxy stack! in .ctor
ContactPoint.exe Error: 0 : [Error] 04/10/2020 17:19:00: Can't initialize PjSIP proxy stack! in .ctor
The program '[9120] ContactPoint.exe' has exited with code 0 (0x0).
`

**Comment by alexrster** [comment]
It looks like you're missing some dependencies - try install latest release: https://github.com/ipphone/core/releases/download/v1.12.694/IP-Phone_core-1.12.694.zip

**Comment by TechGuyVN** [comment]
Thanks @alexrster 
I use win 7 professional service pack 1.
i had install your release too b ut, when open ipphone.exe it exit.
i Viewed your code it got stuck at pjsipWrapper.cs 
` private int start()
        {
            // prepare configuration struct
            // read data from Config interface. If null read all values directly from SipConfigMore
            if (!Config.IsNull)
            {
                ConfigMore.listenPort = Config.SIPPort;
                ConfigMore.rtpPort = Config.RTPPort;
            }

            CommonDelegates.SafeInvoke(() => dll_setSipConfig(ConfigMore));

            int status = CommonDelegates.SafeInvoke(() => { return dll_init(); });
            if (status != 0) return status;

            status = CommonDelegates.SafeInvoke(() => dll_main());
            return status;
        }`
Failed on line:
`            int status = CommonDelegates.SafeInvoke(() => { return dll_init(); });
`

status = 130048

pls check

**Comment by alexrster** [comment]
Do you have any other SIP client running simultaneously?

**Comment by TechGuyVN** [comment]
Yes i can using Zoiper 5 in my machine. @alexrster

**Comment by alexrster** [comment]
What if exit Zoiper 5 and try to start ipphone - still doesn't working?

**Comment by TechGuyVN** [comment]
yes @alexrster still not working, duno why, i had check window Log, nothing exeption :(

**Comment by alexrster** [comment]
Try this branch: https://github.com/ipphone/core/tree/dev/net472

**Comment by alexrster** [comment]
I was able to reproduce this issue on GitHub Actions CI environment and I was able to address it recently by fixing some exports in unmanaged dll and migrating it to latest VC++ Toolset (this is actually the dependency that is installed together with IP Phone). I would kindly ask you to pull latest sources from `master`, try building and running it, and please let me know if it start work for you or not.

Thanks for your feedback!
