### ISSUE TITLE
register to asterisk error

### ISSUE THREAD

**Issue by stevenhzj** [ipphone/core#42]
asterisk 11,when use IP PHONE register to Asterisk server, SIP log display "SIP/2.0 401 Unauthorized"

 14:41:48.805    tsx02E25D24  State changed from Null to Calling, event=TX_MSG
 14:41:48.805    pjsua_acc.c  Registration sent
 14:41:48.812 sip_endpoint.c  Processing incoming message: Response msg 401/REGISTER/cseq=27984 (rdata0AAEB204)
 14:41:48.812   pjsua_core.c  RX 530 bytes Response msg 401/REGISTER/cseq=27984 (rdata0AAEB204) from UDP 192.168.81.26:5060:
SIP/2.0 401 Unauthorized
v: SIP/2.0/UDP 172.22.200.52:5060;branch=z9hG4bKPj3421f0ede67e4f52be6a084a5c8b6798;received=172.22.200.52;rport=5060
f: <sip:8000@192.168.81.26>;tag=df9f12007f13434995c6029c41337f87
t: <sip:8000@192.168.81.26>;tag=as449a4945
i: de5079acf66b4463b78ea6f262778de7
CSeq: 27984 REGISTER
Server: Asterisk PBX 11.3.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH
k: replaces

i use x-lite，it's succeed 

how can i do?

**Comment by alexrster** [comment]
It seems you didn't provide valid configuration settings, so please make sure your settings:
- **Display Name**: _anything you want_
- **Username**: _sip account username_ (usually without domain name part, like: _1001_)
- **Password**: _sip account password_
- **Realm**: * (asterisk symbol)
- **SIP Registrar**: _asterisk server address_ (server IP or DNS name)

Please let me know if this fix your issue!

**Comment by stevenhzj** [comment]
tks ,it's succeed
Realm = *  this line,i write is Server IP, it's wrong.
