### ISSUE TITLE
The Audio is not work

### ISSUE THREAD

**Issue by stevenhzj** [ipphone/core#43]
I register exten at IP PHONE, then make a call to another exten,but is no sound in Audio ,how to setting ?

![image](https://user-images.githubusercontent.com/5153130/88263945-77632580-ccfd-11ea-958d-013f5d392496.png)

**Comment by alexrster** [comment]
Could you please provide some more information from your environment: 
* Windows version, 
* user type, 
* locale, 
* connected audio devices, 
* do you run IP Phone from installation or from source code?

**Comment by stevenhzj** [comment]
> Could you please provide some more information from your environment:
> 
> * Windows version,
    Window 10   
> * user type,
> * locale,
> * connected audio devices,
use  notebook computer audio device
> * do you run IP Phone from installation or from source code?
both test installation and source code

**Comment by stevenhzj** [comment]
so sorry, I make this question is closed.but it not ok
