### ISSUE TITLE
IPPhone.pjsipDll missing

### ISSUE THREAD

**Issue by andrew-paes** [ipphone/core#45]
Hi,

Just did clone the project and when tried to compile, I'm having this issue:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package IPPhone.pjsipDll. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	ContactPoint	D:\Projetos\IpPhone\ContactPoint\ContactPoint.csproj	1	

Where can I find this package?

**Comment by alexrster** [comment]
Should be fixed now

**Comment by wanycn** [comment]
I just try on VS 2019 After clone and build still got same issue. How can I fix it? Where is pjsipDll located

**Comment by alexrster** [comment]
Hi @wanycn,

You can find pjsipdll package here: https://github.com/orgs/ipphone/packages
Try to add nuget package source with above URL in VS settings
