### ISSUE TITLE
Аргументы командной строки

### ISSUE THREAD

**Issue by alex-best** [ipphone/core#63]
Здравстуйте, подскажите пожалуйста, какие аргументы с номером телефона нужно передать, что б позвонить из командной строки?

**Comment by alexrster** [comment]
ContactPoint.exe /call 123456789

On 14 Nov 2020, at 01:21, alex-best <notifications@github.com<mailto:notifications@github.com>> wrote:



Здравстуйте, подскажите пожалуйста, какие аргументы с номером телефона нужно передать, что б позвонить из командной строки?

**Comment by alex-best** [comment]
Спасибо большое
