### ISSUE TITLE
OpenVPN TUN/TAP wrong source IP via SIP registration

### ISSUE THREAD

**Issue by blessendor** [ipphone/core#9]
Программа непонятно себя ведет при использовании в системе OpenVPN туннеля с адресом на TUN/TAP интерфейсе. Причем никакой закономерности - обновляешь сертификат на сервере, или подсеть для нового OpenVPN выдаешь новую - перестает работать. Посылает неверный контакт, например:

  Addr->IP     : 10.1.1.15:5060
  Useragent    : ContactPoint on PJSUA v1.8.10/win32
  Reg. Contact : sip:228@192.168.1.106:5060;ob

10.1.1.15 - адрес на интерфейсе OpenVPN Tun (Windows 10), но контакт регистрируется с его WiFi-интерфейса 192.168.1.106. 

Другой диапазон OpenVPN сети (1.1.1.0/24) - и такой проблемы нет:
  Addr->IP     : 1.1.1.37:5060
  Status       : OK (45 ms)
  Useragent    : ContactPoint on PJSUA v1.8.10/win32
  Reg. Contact : sip:182@1.1.1.37:5060;ob

При тех же условиях PhonerLite посылает верную регистрацию.
PhonerLite:
  Addr->IP     : 10.1.1.7:5060
  Status       : OK (40 ms)
  Useragent    : SIPPER for PhonerLite
  Reg. Contact : sip:318@10.1.1.7:5060

**Comment by alexrster** [comment]
Да - думаю такое вполне вероятно! Думаю нужно этот параметр вынести в настройки

**Comment by blessendor** [comment]
Только IP адрес VPN пул выдает случайный, явно его не укажешь в какое-либо поле source_ip программы. Такое еще бывало на виндах 7, но помогало выгрузить телефон, рестартовать впн и загрузить телефон. На 10-ке усугубилось почему-то.

**Comment by alexrster** [comment]
Нужно смотреть логи:
* Запустите консоль от имени администратора
* Перейдите в папку с IPPhone
* Запустите `ContactPoint.exe /loglevel 10 /log debug.log`
* Воспроизведите баг
* Закройте IPPhone
* Сбросьте сюда лог файлы с текущей папки: `debug.log` и `pjsip.log`

**Comment by blessendor** [comment]
Запуск
http://take.ms/DHaQv

Лога нет
http://take.ms/9o2XS

**Comment by blessendor** [comment]
pjsip.log
http://pasted.co/5444ba6f

**Comment by alexrster** [comment]
Спасибо за логи - разобрался!

1. Согласно `rfc3581` используется параметр `received` в хедере `Via` для работы через нат:
```
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.31.116:5061;branch=z9hG4b...;received=10.1.1.42;rport=5061
From: sip:192@192.168.100.100;tag=b8824e579059442984573c8c9b5ade2b
To: sip:0501111111@192.168.100.100;tag=as03f73086
Call-ID: 20c4c790677d4008a045e9bba6f71dfe
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;более подробно: https://thanhloi2603.wordpress.com/2017/05/02/lets-play-sip-received-and-rport/


2. Если для Вас это значение критично - можно в настройках программы указывать имя пользователя вместе с его айпи адресом, например в Вашем случае: `192@10.1.1.15`

3. В случае динамического пула адресов используйте DNS имя: `192@pc11.vpn.local`

**Comment by blessendor** [comment]
Я не понял комментарий, что received использован верно.

Смотрите на скрине подобный пример - в нем верный IP received=10.1.1.3.

http://take.ms/etpfz

И это не случай NAT для Asterisk - данная подсеть состоит в в списке локальных для него сетей, иначе бы астериск вообще подставлял клиенту свой внешний адрес в rtp.

**Comment by blessendor** [comment]
Что-то с редиректом у take.ms
Вот прямая ссылка на скрин
https://monosnap.com/file/lS2M8eENhg0ynylWyJcxryj155OSeS

**Comment by blessendor** [comment]
Проблема, в общем, решается установкой данным пользователям на стороне asterisk параметра 

**nat=force_rport,comedia** (было nat=no)

На изменение адреса в Contact это никак не влияет (все тот же неверный), но на доступности пира помогает (вход/исход работают).
....
  Force rport  : Yes
  Symmetric RTP: Yes
...
Addr->IP     : 10.1.1.42:5061
  Defaddr->IP  : (null)
  Prim.Transp. : UDP                                                                                                                                                                                                             
  Allowed.Trsp : UDP
...                                                                                                                                                                                              
  Status       : OK (52 ms)
  Useragent    : ContactPoint on PJSUA v1.8.10/win32
  Reg. Contact : sip:192@192.168.31.116:5061;ob
